api_platform:
  title: 'Blogium API'
  description: 'An API to fetch blogs and post new ones'
  version: '1.0.0'
  mapping:
    paths:
      - '%kernel.project_dir%/src/Infrastructure/Api/BlogPost/blogpost.api.yaml'
      - '%kernel.project_dir%/src/Infrastructure/Api/User/user.api.yaml'