App\Entity\BlogPost:
    properties:
        title:
            - Length: 
                min: 5
                minMessage: 'The title must be longer than {{ limit }}'
                max: 255
                maxMessage: 'The title must be shorter than {{ limit }}'
        body:
            - Length:
                min: 5
                minMessage: 'The body must be longer than {{ limit }}'