blogs:
    path: /
    controller: App\Controller\ListBlogController::listBlogs
    methods: [ 'GET' ]

blog:
    path: /blogs/{slug}/{id}
    controller: App\Controller\ShowBlogController::showBlog
    requirements:
        id: \d+

login:
    path: /login
    controller: App\Controller\LoginController::login

show_register:
    path: /register
    controller: App\Controller\ShowRegisterController::showRegister
    methods: [ 'GET' ]

register:
    path: /register
    controller: App\Controller\RegisterController::register
    methods: [ 'POST' ]

secured:
    path: /secured
    controller: App\Controller\SecuredController::index
    methods: [ 'GET' ]
    
logout:
    path: /logout
    controller: App\Controller\LogoutController::logout