blogs:
    path: /
    controller: App\Infrastructure\Controller\BlogPost\ListBlogController::listBlogs
    methods: [ 'GET' ]

blog:
    path: /blogs/{slug}/{id}
    controller: App\Infrastructure\Controller\BlogPost\ShowBlogController::showBlog
    requirements:
        id: \d+

login:
    path: /login
    controller: App\Infrastructure\Controller\User\LoginController::login

show_register:
    path: /register
    controller: App\Infrastructure\Controller\User\ShowRegisterController::showRegister
    methods: [ 'GET' ]

register:
    path: /register
    controller: App\Infrastructure\Controller\User\RegisterController::register
    methods: [ 'POST' ]

secured:
    path: /secured
    controller: App\Infrastructure\Controller\User\SecuredController::index
    methods: [ 'GET' ]
    
logout:
    path: /logout
    controller: App\Infrastructure\Controller\User\LogoutController::logout

api_login:
    path: /api/login_check